package br.gov.se.lai.entity;
// Generated 18/09/2017 08:12:36 by Hibernate Tools 5.2.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Competencias generated by hbm2java
 */
@Entity
@Table(name = "competencias", catalog = "esic")
public class Competencias implements java.io.Serializable {


	private static final long serialVersionUID = 4280308292400672741L;
	private Integer idCompetencias;
	private Acoes acoes;
	private Entidades entidades;
	private String descricao;

	public Competencias() {
	}

	public Competencias(Acoes acoes, Entidades entidades) {
		this.acoes = acoes;
		this.entidades = entidades;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idCompetencias", unique = true, nullable = false)
	public Integer getIdCompetencias() {
		return this.idCompetencias;
	}

	public void setIdCompetencias(Integer idCompetencias) {
		this.idCompetencias = idCompetencias;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idAcoes", nullable = false)
	public Acoes getAcoes() {
		return this.acoes;
	}

	public void setAcoes(Acoes acoes) {
		this.acoes = acoes;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idEntidades", nullable = false)
	public Entidades getEntidades() {
		return this.entidades;
	}

	public void setEntidades(Entidades entidades) {
		this.entidades = entidades;
	}


	@JoinColumn(name = "Descricao", nullable = false)
	public String getDescricao() {
		return descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

}
