package br.gov.se.lai.entity;
// Generated 30/08/2017 11:22:29 by Hibernate Tools 5.2.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Entidades generated by hbm2java
 */
@Entity
@Table(name = "entidades", catalog = "esic")
public class Entidades implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1650340458189757832L;
	private int idEntidades;
	private Orgaos orgaos;
	private String nome;
	private String setor;
	private String contatoEntid;
	private Set<Solicitacao> solicitacaos = new HashSet<Solicitacao>(0);
	private Set<Responsavel> responsavels = new HashSet<Responsavel>(0);
	private Set<Acoes> acoeses = new HashSet<Acoes>(0);

	public Entidades() {
	}

	public Entidades(int idEntidades, Orgaos orgaos, String nome) {
		this.idEntidades = idEntidades;
		this.orgaos = orgaos;
		this.nome = nome;
	}

	public Entidades(int idEntidades, Orgaos orgaos, String nome, String setor, String contatoEntid, Set<Solicitacao> solicitacaos,
			Set<Responsavel> responsavels, Set<Acoes> acoeses) {
		this.idEntidades = idEntidades;
		this.orgaos = orgaos;
		this.nome = nome;
		this.setor = setor;
		this.contatoEntid = contatoEntid;
		this.solicitacaos = solicitacaos;
		this.responsavels = responsavels;
		this.acoeses = acoeses;
	}

	@Id

	@Column(name = "idEntidades", unique = true, nullable = false)
	public int getIdEntidades() {
		return this.idEntidades;
	}

	public void setIdEntidades(int idEntidades) {
		this.idEntidades = idEntidades;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idOrgaos", nullable = false)
	public Orgaos getOrgaos() {
		return this.orgaos;
	}

	public void setOrgaos(Orgaos orgaos) {
		this.orgaos = orgaos;
	}

	@Column(name = "nome", nullable = false, length = 45)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "setor", length = 45)
	public String getSetor() {
		return this.setor;
	}

	public void setSetor(String setor) {
		this.setor = setor;
	}

	@Column(name = "contatoEntid", length = 12)
	public String getContatoEntid() {
		return this.contatoEntid;
	}

	public void setContatoEntid(String contatoEntid) {
		this.contatoEntid = contatoEntid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "entidades")
	public Set<?> getSolicitacaos() {
		return this.solicitacaos;
	}

	public void setSolicitacaos(Set<Solicitacao> solicitacaos) {
		this.solicitacaos = solicitacaos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "entidades")
	public Set<?> getResponsavels() {
		return this.responsavels;
	}

	public void setResponsavels(Set<Responsavel> responsavels) {
		this.responsavels = responsavels;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "entidadeses")
	public Set<?> getAcoeses() {
		return this.acoeses;
	}

	public void setAcoeses(Set<Acoes> acoeses) {
		this.acoeses = acoeses;
	}

}
