package br.gov.se.lai.entity;
// Generated 04/09/2017 09:25:00 by Hibernate Tools 5.2.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Entidades generated by hbm2java
 */
@Entity
@Table(name = "entidades", catalog = "esic")
public class Entidades implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1597754383085083739L;
	private Integer idEntidades;
	private Orgaos orgaos;
	private String nome;
	private String setor;
	private String contatoEntid;
	private Set<Responsavel> responsavels = new HashSet<Responsavel>(0);
	private Set<Solicitacao> solicitacaos = new HashSet<Solicitacao>(0);
	private Set<Competencias> competenciases = new HashSet<Competencias>(0);

	public Entidades() {
	}

	public Entidades(Orgaos orgaos, String nome) {
		this.orgaos = orgaos;
		this.nome = nome;
	}

	public Entidades(Orgaos orgaos, String nome, String setor, String contatoEntid, Set<Responsavel> responsavels,
			Set<Solicitacao> solicitacaos, Set<Competencias> competenciases) {
		this.orgaos = orgaos;
		this.nome = nome;
		this.setor = setor;
		this.contatoEntid = contatoEntid;
		this.responsavels = responsavels;
		this.solicitacaos = solicitacaos;
		this.competenciases = competenciases;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idEntidades", unique = true, nullable = false)
	public Integer getIdEntidades() {
		return this.idEntidades;
	}

	public void setIdEntidades(Integer idEntidades) {
		this.idEntidades = idEntidades;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idOrgaos", nullable = false)
	public Orgaos getOrgaos() {
		return this.orgaos;
	}

	public void setOrgaos(Orgaos orgaos) {
		this.orgaos = orgaos;
	}

	@Column(name = "nome", nullable = false, length = 45)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "setor", length = 45)
	public String getSetor() {
		return this.setor;
	}

	public void setSetor(String setor) {
		this.setor = setor;
	}

	@Column(name = "contatoEntid", length = 12)
	public String getContatoEntid() {
		return this.contatoEntid;
	}

	public void setContatoEntid(String contatoEntid) {
		this.contatoEntid = contatoEntid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "entidades")
	public Set<Responsavel> getResponsavels() {
		return this.responsavels;
	}

	public void setResponsavels(Set<Responsavel> responsavels) {
		this.responsavels = responsavels;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "entidades")
	public Set<Solicitacao> getSolicitacaos() {
		return this.solicitacaos;
	}

	public void setSolicitacaos(Set<Solicitacao> solicitacaos) {
		this.solicitacaos = solicitacaos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "entidades")
	public Set<Competencias> getCompetenciases() {
		return this.competenciases;
	}

	public void setCompetenciases(Set<Competencias> competenciases) {
		this.competenciases = competenciases;
	}

}
