package br.gov.se.lai.entity;
// Generated 18/09/2017 08:12:36 by Hibernate Tools 5.2.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Mensagem generated by hbm2java
 */
@Entity
@Table(name = "mensagem", catalog = "esic")
public class Mensagem implements java.io.Serializable {


	private static final long serialVersionUID = -4273056639466954495L;
	private Integer idMensagem;
	private Solicitacao solicitacao;
	private Usuario usuario;
	private String texto;
	private Date data;
	private short tipo;
	private Integer nota;
	private Set<Anexo> anexos = new HashSet<Anexo>(0);

	public Mensagem() {
	}

	public Mensagem(Solicitacao solicitacao, Usuario usuario) {
		this.solicitacao = solicitacao;
		this.usuario = usuario;
	}

	public Mensagem(Solicitacao solicitacao, Usuario usuario, String texto, Date data, short tipo, Set<Anexo> anexos) {
		this.solicitacao = solicitacao;
		this.usuario = usuario;
		this.texto = texto;
		this.data = data;
		this.tipo = tipo;
		this.anexos = anexos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idMensagem", unique = true, nullable = false)
	public Integer getIdMensagem() {
		return this.idMensagem;
	}

	public void setIdMensagem(Integer idMensagem) {
		this.idMensagem = idMensagem;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idSolicitacao", nullable = false)
	public Solicitacao getSolicitacao() {
		return this.solicitacao;
	}

	public void setSolicitacao(Solicitacao solicitacao) {
		this.solicitacao = solicitacao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idUsuario", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "texto", length = 65535)
	public String getTexto() {
		return this.texto;
	}

	public void setTexto(String texto) {
		this.texto = texto;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data", length = 19)
	public Date getData() {
		return this.data;
	}

	public void setData(Date data) {
		this.data = data;
	}
	
	@Column(name = "tipo")
	public Short getTipo() {
		return this.tipo;
	}

	public void setTipo(Short tipo) {
		this.tipo = tipo;
	}

	
	@Column(name = "nota")
	public Integer getNota() {
		return nota;
	}

	public void setNota(Integer nota) {
		this.nota = nota;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mensagem")
	public Set<Anexo> getAnexos() {
		return this.anexos;
	}

	public void setAnexos(Set<Anexo> anexos) {
		this.anexos = anexos;
	}

}
