package br.gov.se.lai.Entity;
// Generated 30/08/2017 11:22:29 by Hibernate Tools 5.2.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Orgaos generated by hbm2java
 */
@Entity
@Table(name = "orgaos", catalog = "esic")
public class Orgaos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1301795054786267019L;
	private int idOrgaos;
	private String nome;
	private Set<Entidades> entidadeses = new HashSet<Entidades>(0);

	public Orgaos() {
	}

	public Orgaos(int idOrgaos, String nome) {
		this.idOrgaos = idOrgaos;
		this.nome = nome;
	}

	public Orgaos(int idOrgaos, String nome, Set<Entidades> entidadeses) {
		this.idOrgaos = idOrgaos;
		this.nome = nome;
		this.entidadeses = entidadeses;
	}

	@Id

	@Column(name = "idOrgaos", unique = true, nullable = false)
	public int getIdOrgaos() {
		return this.idOrgaos;
	}

	public void setIdOrgaos(int idOrgaos) {
		this.idOrgaos = idOrgaos;
	}

	@Column(name = "nome", nullable = false, length = 45)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orgaos")
	public Set<Entidades> getEntidadeses() {
		return this.entidadeses;
	}

	public void setEntidadeses(Set<Entidades> entidadeses) {
		this.entidadeses = entidadeses;
	}

}
