package br.gov.se.lai.entity;
// Generated 04/09/2017 09:25:00 by Hibernate Tools 5.2.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Representante generated by hbm2java
 */
@Entity
@Table(name = "representante", catalog = "esic")
public class Representante implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1860085728262047737L;
	private Integer idRepresentante;
	private Usuario usuario;
	private Set<Responsavel> responsavels = new HashSet<Responsavel>(0);

	public Representante() {
	}

	public Representante(Usuario usuario) {
		this.usuario = usuario;
	}

	public Representante(Usuario usuario, Set<Responsavel> responsavels) {
		this.usuario = usuario;
		this.responsavels = responsavels;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idRepresentante", unique = true, nullable = false)
	public Integer getIdRepresentante() {
		return this.idRepresentante;
	}

	public void setIdRepresentante(Integer idRepresentante) {
		this.idRepresentante = idRepresentante;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idUsuario", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "representante")
	public Set<Responsavel> getResponsavels() {
		return this.responsavels;
	}

	public void setResponsavels(Set<Responsavel> responsavels) {
		this.responsavels = responsavels;
	}

}
