package br.gov.se.lai.entity;
// Generated 30/08/2017 11:22:29 by Hibernate Tools 5.2.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ResponsavelId generated by hbm2java
 */
@Embeddable
public class ResponsavelId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4594136223390704217L;
	private int idRepresentante;
	private int idEntidades;

	public ResponsavelId() {
	}

	public ResponsavelId(int idRepresentante, int idEntidades) {
		this.idRepresentante = idRepresentante;
		this.idEntidades = idEntidades;
	}

	@Column(name = "idRepresentante", nullable = false)
	public int getIdRepresentante() {
		return this.idRepresentante;
	}

	public void setIdRepresentante(int idRepresentante) {
		this.idRepresentante = idRepresentante;
	}

	@Column(name = "idEntidades", nullable = false)
	public int getIdEntidades() {
		return this.idEntidades;
	}

	public void setIdEntidades(int idEntidades) {
		this.idEntidades = idEntidades;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ResponsavelId))
			return false;
		ResponsavelId castOther = (ResponsavelId) other;

		return (this.getIdRepresentante() == castOther.getIdRepresentante())
				&& (this.getIdEntidades() == castOther.getIdEntidades());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdRepresentante();
		result = 37 * result + this.getIdEntidades();
		return result;
	}

}
