package br.gov.se.lai.entity;
// Generated 18/09/2017 08:12:36 by Hibernate Tools 5.2.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Responsavel generated by hbm2java
 */
@Entity
@Table(name = "responsavel", catalog = "esic")
public class Responsavel implements java.io.Serializable {


	private static final long serialVersionUID = 4683753718646281832L;
	private Integer idResponsavel;
	private Entidades entidades;
	private Usuario usuario;
	private Short nivel;
	private String email;
	private String telefone1;
	private String telefone2;
	private boolean ativo;

	public Responsavel() {
	}

	public Responsavel(Entidades entidades, boolean ativo, Usuario usuario, String email) {
		this.entidades = entidades;
		this.usuario = usuario;
		this.email = email;
		this.ativo = ativo;
	}

	public Responsavel(Entidades entidades, boolean ativo, Usuario usuario, Short nivel, String email, String telefone1, String telefone2) {
		this.entidades = entidades;
		this.usuario = usuario;
		this.nivel = nivel;
		this.email = email;
		this.ativo = ativo;
		this.telefone1 = telefone1;
		this.telefone2 = telefone2;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idResponsavel", unique = true, nullable = false)
	public Integer getIdResponsavel() {
		return this.idResponsavel;
	}

	public void setIdResponsavel(Integer idResponsavel) {
		this.idResponsavel = idResponsavel;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idEntidades", nullable = false)
	public Entidades getEntidades() {
		return this.entidades;
	}

	public void setEntidades(Entidades entidades) {
		this.entidades = entidades;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idUsuario", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "nivel")
	public Short getNivel() {
		return this.nivel;
	}

	public void setNivel(Short nivel) {
		this.nivel = nivel;
	}

	@Column(name = "email", nullable = false, length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "ativo", nullable = false, length = 1 )
	public boolean isAtivo() {
		return ativo;
	}

	public void setAtivo(boolean ativo) {
		this.ativo = ativo;
	}
	
	@Column(name = "telefone1", nullable = false, length = 20)
	public String getTelefone1() {
		return telefone1;
	}

	public void setTelefone1(String telefone1) {
//		String x = telefone1;
//		if (x.length() == 14) {
//			x = x.substring(0, x.length()-4) + "-" + x.substring(x.length()-4);
//			x = x.substring(0, x.length()-9) + " " + x.substring(x.length()-9);
//			this.telefone1 = x;
//		} else if (x.length() == 13) {
//			x = x.substring(0, x.length()-4) + "-" + x.substring(x.length()-4);
//			this.telefone1 = x;
//		} else
			this.telefone1 = telefone1;
	}
	
	@Column(name = "telefone2", nullable = false, length = 20)
	public String getTelefone2() {
		return telefone2;
	}

	public void setTelefone2(String telefone2) {
//		String x = telefone2;
//		if (x.length() == 14) {
//			x = x.substring(0, x.length()-4) + "-" + x.substring(x.length()-4);
//			x = x.substring(0, x.length()-9) + " " + x.substring(x.length()-9);
//			this.telefone2 = x;
//		} else if (x.length() == 13) {
//			x = x.substring(0, x.length()-4) + "-" + x.substring(x.length()-4);
//			this.telefone2 = x;
//		} else
			this.telefone2 = telefone2;
	}

	
}
