package br.gov.se.lai.Entity;
// Generated 30/08/2017 11:22:29 by Hibernate Tools 5.2.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Responsavel generated by hbm2java
 */
@Entity
@Table(name = "responsavel", catalog = "esic")
public class Responsavel implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5382999195316919265L;
	private ResponsavelId id;
	private Entidades entidades;
	private Representante representante;
	private Short nivel;
	private String email;

	public Responsavel() {
	}

	public Responsavel(ResponsavelId id, Entidades entidades, Representante representante, String email) {
		this.id = id;
		this.entidades = entidades;
		this.representante = representante;
		this.email = email;
	}

	public Responsavel(ResponsavelId id, Entidades entidades, Representante representante, Short nivel, String email) {
		this.id = id;
		this.entidades = entidades;
		this.representante = representante;
		this.nivel = nivel;
		this.email = email;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idRepresentante", column = @Column(name = "idRepresentante", nullable = false)),
			@AttributeOverride(name = "idEntidades", column = @Column(name = "idEntidades", nullable = false)) })
	public ResponsavelId getId() {
		return this.id;
	}

	public void setId(ResponsavelId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idEntidades", nullable = false, insertable = false, updatable = false)
	public Entidades getEntidades() {
		return this.entidades;
	}

	public void setEntidades(Entidades entidades) {
		this.entidades = entidades;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idRepresentante", nullable = false, insertable = false, updatable = false)
	public Representante getRepresentante() {
		return this.representante;
	}

	public void setRepresentante(Representante representante) {
		this.representante = representante;
	}

	@Column(name = "nivel")
	public Short getNivel() {
		return this.nivel;
	}

	public void setNivel(Short nivel) {
		this.nivel = nivel;
	}

	@Column(name = "email", nullable = false, length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}
