package br.gov.se.lai.entity;
// Generated 30/08/2017 11:22:29 by Hibernate Tools 5.2.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Solicitacao generated by hbm2java
 */
@Entity
@Table(name = "solicitacao", catalog = "esic")
public class Solicitacao implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 182603986971587517L;
	private int idSolicitacao;
	private Cidadao cidadao;
	private Entidades entidades;
	private Date dataIni;
	private String status;
	private Date datafim;
	private String titulo;
	private Short assunto;
	private Set< Mensagem> mensagems = new HashSet<Mensagem>(0);

	public Solicitacao() {
	}

	public Solicitacao(int idSolicitacao, Cidadao cidadao, Entidades entidades) {
		this.idSolicitacao = idSolicitacao;
		this.cidadao = cidadao;
		this.entidades = entidades;
	}

	public Solicitacao(int idSolicitacao, Cidadao cidadao, Entidades entidades, Date dataIni, String status,
			Date datafim, String titulo, Short assunto, Set< Mensagem> mensagems) {
		this.idSolicitacao = idSolicitacao;
		this.cidadao = cidadao;
		this.entidades = entidades;
		this.dataIni = dataIni;
		this.status = status;
		this.datafim = datafim;
		this.titulo = titulo;
		this.assunto = assunto;
		this.mensagems = mensagems;
	}

	@Id

	@Column(name = "idSolicitacao", unique = true, nullable = false)
	public int getIdSolicitacao() {
		return this.idSolicitacao;
	}

	public void setIdSolicitacao(int idSolicitacao) {
		this.idSolicitacao = idSolicitacao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idCidadao", nullable = false)
	public Cidadao getCidadao() {
		return this.cidadao;
	}

	public void setCidadao(Cidadao cidadao) {
		this.cidadao = cidadao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idEntidades", nullable = false)
	public Entidades getEntidades() {
		return this.entidades;
	}

	public void setEntidades(Entidades entidades) {
		this.entidades = entidades;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dataIni", length = 10)
	public Date getDataIni() {
		return this.dataIni;
	}

	public void setDataIni(Date dataIni) {
		this.dataIni = dataIni;
	}

	@Column(name = "status", length = 10)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "datafim", length = 10)
	public Date getDatafim() {
		return this.datafim;
	}

	public void setDatafim(Date datafim) {
		this.datafim = datafim;
	}

	@Column(name = "titulo", length = 45)
	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	@Column(name = "assunto")
	public Short getAssunto() {
		return this.assunto;
	}

	public void setAssunto(Short assunto) {
		this.assunto = assunto;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "solicitacao")
	public Set<?> getMensagems() {
		return this.mensagems;
	}

	public void setMensagems(Set< Mensagem> mensagems) {
		this.mensagems = mensagems;
	}

}
