package br.gov.se.lai.entity;
// Generated 18/09/2017 08:12:36 by Hibernate Tools 5.2.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", catalog = "esic")
public class Usuario implements java.io.Serializable {


	private static final long serialVersionUID = -2380284948334048659L;
	private Integer idUsuario;
	private String nome;
	private String nick;
	private String senha;
	private String sessionId;
	private short perfil;
	private Date lastLogged;
	private Set<Mensagem> mensagems = new HashSet<Mensagem>(0);
	private Set<Cidadao> cidadaos = new HashSet<Cidadao>(0);
	private Set<Responsavel> responsavels = new HashSet<Responsavel>(0);
	private boolean migrado;

	public Usuario() {
	}

	public Usuario(String nome, String nick, String senha, short perfil, Date lastLogged, String sessionId) {
		this.nome = nome;
		this.nick = nick;
		this.senha = senha;
		this.perfil = perfil;
		this.lastLogged = lastLogged;
		this.sessionId = sessionId;
	}

	public Usuario(String nome, String nick, String senha, short perfil, Set<Mensagem> mensagems, Set<Cidadao> cidadaos,
			Set<Responsavel> responsavels, Date lastLogged, String sessionId) {
		this.nome = nome;
		this.nick = nick;
		this.senha = senha;
		this.perfil = perfil;
		this.mensagems = mensagems;
		this.cidadaos = cidadaos;
		this.responsavels = responsavels;
		this.lastLogged = lastLogged;
		this.sessionId = sessionId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idUsuario", unique = true, nullable = false)
	public Integer getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(Integer idUsuario) {
		this.idUsuario = idUsuario;
	}

	@Column(name = "nome", nullable = false, length = 100)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "nick", nullable = false, length = 100)
	public String getNick() {
		return this.nick;
	}

	public void setNick(String nick) {
		this.nick = nick;
	}

	@Column(name = "senha", nullable = false, length = 64)
	public String getSenha() {
		return this.senha;
	}

	public void setSenha(String senha) {
		this.senha = senha;
	}

	@Column(name = "perfil", nullable = false)
	public short getPerfil() {
		return this.perfil;
	}

	public void setPerfil(short perfil) {
		this.perfil = perfil;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<Mensagem> getMensagems() {
		return this.mensagems;
	}

	public void setMensagems(Set<Mensagem> mensagems) {
		this.mensagems = mensagems;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<Cidadao> getCidadaos() {
		return this.cidadaos;
	}

	public void setCidadaos(Set<Cidadao> cidadaos) {
		this.cidadaos = cidadaos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<Responsavel> getResponsavels() {
		return this.responsavels;
	}

	public void setResponsavels(Set<Responsavel> responsavels) {
		this.responsavels = responsavels;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastLogged", length = 19)
	public Date getLastLogged() {
		return lastLogged;
	}

	public void setLastLogged(Date last_logged) {
		this.lastLogged = last_logged;
	}

	@Column(name = "sessionId", length = 45)
	public String getSessionId() {
		return sessionId;
	}

	public void setSessionId(String sessionId) {
		this.sessionId = sessionId;
	}

	@Column(name = "migrado", nullable = false)
	public boolean isMigrado() {
		return migrado;
	}

	public void setMigrado(boolean migrado) {
		this.migrado = migrado;
	}
	
	
	

}
